### PR TITLE
Upgrade to support Cosmwasm 2

### PR DESCRIPTION
**Pull request by masihyeganeh**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/test-tube/9#-O9Ep9zCBNdibQZyvUTD:-O9Ep9zCBNdibQZyvUTE:bi5saxr) (no related file):*
You need a better title

___
___
*[`packages/coreum-test-tube/Cargo.toml` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/test-tube/9#-O9EpMMJ-EvHwyNxRhSV:-O9EpMMJ-EvHwyNxRhSW:bn1j2v) ([raw file](https://github.com/CoreumFoundation/test-tube/blob/1431bcf8e7e8f599d8c0f72fa5adda192f882693/packages/coreum-test-tube/Cargo.toml#L7)):*
> ```TOML
> repository = "https://github.com/CoreumFoundation/test-tube"
> name = "coreum-test-tube"
> version = "4.1.0"
> ```

we have upgrade to cosmwasm v2 only in the master branch, which will be released in the v5 release, so may be we should wait with the release v5 before we publish this into cargo. or discuss it in the team.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

*[a discussion](https://reviewable.io/reviews/CoreumFoundation/test-tube/9#-O9Ep9zCBNdibQZyvUTD:-O9Joyuf93TRcXipMdOt:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

You need a better title
</blockquote></details>

Done.

___

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`packages/coreum-test-tube/Cargo.toml` line 7 at r1](https://reviewable.io/reviews/CoreumFoundation/test-tube/9#-O9EpMMJ-EvHwyNxRhSV:-O9Jp-wY5R009ju_nTrW:b-pmyygx) ([raw file](https://github.com/CoreumFoundation/test-tube/blob/1431bcf8e7e8f599d8c0f72fa5adda192f882693/packages/coreum-test-tube/Cargo.toml#L7)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

we have upgrade to cosmwasm v2 only in the master branch, which will be released in the v5 release, so may be we should wait with the release v5 before we publish this into cargo. or discuss it in the team.
</blockquote></details>

We can merge this to master, but we need to wait for v5 release before publishing the cargo package

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/9#-:-O9UTTmG2zYExARmxdej:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Pull request merged**
