### PR TITLE
Release version `4.0.0` of test-tube

### PR DESCRIPTION
**Pull request by wojtek-coreum**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/7)

### CODE REVIEW

**Review by wojtek-coreum — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/7)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @dzmitryhil, @miladz68, and @ysv)

___
*[`.github/workflows/release.yml` line 44 at r1](https://reviewable.io/reviews/CoreumFoundation/test-tube/7#-O-uZYdC9ZHtgN6QINHd:-O-ue8uL1HppYeoFmQ5T:bqpop4v) ([raw file](https://github.com/CoreumFoundation/test-tube/blob/b83e06bc66bc125a119713ce023adf75f9d209ce/.github/workflows/release.yml#L44)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

So you publish the crates even is you use the RC ? Why do you need the RC at all then?
</blockquote></details>

Because then we release the RC version

**Review by miladz68 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/7)* status: all files reviewed, 1 unresolved discussion (waiting on @dzmitryhil and @ysv)

**Review by dzmitryhil — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ysv)

**Review by dzmitryhil — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh, @miladz68, and @ysv)

**Review by miladz68 — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/test-tube/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @masihyeganeh and @ysv)

**Pull request merged**
